### ISSUE TITLE
least privilege MongoDB user for nagios-plugin-mongodb

### ISSUE THREAD

**Issue by GETandSELECT** [mzupan/nagios-plugin-mongodb#170]
How did you made a least privilege MongoDB user for nagios-plugin-mongodb? Did you use any Built-In Roles?

From a security point of view there is no need for Nagios plugin to access actual data.

thank you very much

**Comment by warrenpnz** [comment]
Depends on the version of MongoDb that you are running, as some roles do not exists in earlier versions, so:

MongoDB 2.4:
'roles' : [ 'readAnyDatabase', 'clusterAdmin' ],
'otherDBRoles' : { 'nagios' : [ 'readWrite' ] }

MongoDB 2.6+:
'roles' : [ 'readAnyDatabase', 'clusterMonitor' ],
'otherDBRoles' : { 'nagios' : [ 'readWrite' ] }

Bear in mind that you may need read/write to the local db if my pull request doesn't get put through

**Comment by witchbutter** [comment]
This is not working with 3.2.3.  I tried using our existing user which failed and then I used this command verbatim and it also fails:

$  check_mongodb.py -H 'host.somedomain.com' -D -A queries_per_second -P 27017 -u nagios -p password -W 150 -C 200 -q update
Output: CRITICAL - General MongoDB Error: command SON([('authenticate', 1), ('user', u'nagios'), ('nonce', u'60863e966f72c292'), ('key', u'aded54c378b0a787ddccacfd295180d5')]) failed: auth failed
Errors:
Return code: 2

**Comment by warrenpnz** [comment]
The authentication database is hard coded to use admin. I had put a pull request in to allow for an "--authdb" swicth to allow for other dbs to be used. So is your nagios user in the admin db?

**Comment by witchbutter** [comment]
It is in admin.  I am looking at the pymongo driver also which for CentOS 7.2 is python-pymongo-2.5.2-4.el7.x86_64.  I wonder could there be something new with the connection method?

> db.getUser("nagios")
{
	"_id" : "admin.nagios",
	"user" : "nagios",
	"db" : "admin",
	"roles" : [
		{
			"role" : "readAnyDatabase",
			"db" : "admin"
		},
		{
			"role" : "clusterAdmin",
			"db" : "admin"
		},
		{
			"role" : "readWrite",
			"db" : "nagios"
		},
		{
			"role" : "readWrite",
			"db" : "local"
		}
	]
}
>

**Comment by warrenpnz** [comment]
Pymongo 2.3+ and Mongo 3.2.3 should work with the check_mongo.py script as is. Hmmm....I'm assuming that you are using the latest version of the check script?

**Comment by witchbutter** [comment]
For the sake of argument I redownloaded it and replaced it. but the issue is the same.

**Comment by warrenpnz** [comment]
As a control, can you run up a new mongo instance on a workstation with clean dbs and a bare config file, e.g:
```
# Logging configuration (don't write log file/stdout, just write to syslog)
systemLog:
   destination: file
   path: /data/db/mongod.log
   logAppend: true
# Storage engine options
storage:
   engine: wiredTiger
   journal:
      enabled: true
processManagement:
   # Path to pidfile
   pidFilePath: /data/db/mongod.pid
   fork: true
```
Then create the nagios user and try the check script.
